### ISSUE TITLE
Suggestion - Radars

### ISSUE THREAD

**Issue by apemanzilla** [demipixel/autotorio#1]
First off, amazing job with this! It's _really_ helpful for lazy people like me!

I like to place radars in my outposts so I can keep an eye on things from a distance, so it would be neat if the tool could add radars somewhere in the free space.

**Comment by demipixel** [comment]
Yep, Xterminator5 suggested this, already had it in mind :)

**Comment by demipixel** [comment]
Implemented in next version.

**Comment by demipixel** [comment]
Live.

**Comment by apemanzilla** [comment]
Thanks!
