### ISSUE TITLE
Copy to Clipboard Button?

### ISSUE THREAD

**Issue by nelsonjchen** [demipixel/autotorio#10]
It's very handy in Factorio that when you ask it to export a string that there's a handy button to click and copy the string to the clipboard. Perhaps this tool could use the same thing on the blueprint result dialog?

I would have put a pull request out but I was having some serious trouble building this project. Maybe it might be worth adding some CI so at least there's some tested "documentation" on building this? That's another issue. Anyway, I would have looked [here][1] to start adding this feature and this little tidbit of code.

```
document.execCommand("copy");
```

[1]: https://github.com/demipixel/autotorio/blob/4be526259f8558fac89df4286c979b8683b09959/assets/js/handleForm.js#L40

**Comment by demipixel** [comment]
Done!
