### ISSUE TITLE
Explanation 

### ISSUE THREAD

**Issue by ExRed** [demipixel/autotorio#11]
I think there should be an explanation on the page itself on how to use it. I came from reddit, so I know. But  if I would send this cool webpage to a friend, he wouldnt know that he needs to place walls or import blueprints in order to use this website.

**Comment by demipixel** [comment]
Yeah, but I agree it needs to be better, it's not exactly obvious...

**Comment by demipixel** [comment]
Thank you @OriginalsByToto !
