### ISSUE TITLE
add feature for removing items

### ISSUE THREAD

**Issue by nmbro** [demipixel/autotorio#12]
Instead of being able to replace stuff like concrete - I would like the be able to just remove it.

**Comment by demipixel** [comment]
I'll consider this. The main reason I haven't added this is because you can simply use a filter on a deconstruction planner.

**Comment by nmbro** [comment]
Oh nice... I love learning new things about factorio! XD

**Comment by demipixel** [comment]
As of 0.16, creating a blueprint will not include items marked for deconstruction, so to imitate this you can now place your blueprint, whitelist concrete and mark it for deconstruction, and then take a blueprint again.
