### ISSUE TITLE
Does not account for rail grid snapping

### ISSUE THREAD

**Issue by fwyrl** [demipixel/autotorio#2]
As per title, it ignores rail grid snapping. In (very) rare cases, this can make it so that you cannot line up the miners with the ore patch properly. Maybe add a checkbox for moving the miners one block down/right/both (or up/left/both)? Or, you could always allow the player to drop a rail segment onto the ore patch in the input blueprint, and use that to align the miners, but that'd be more work on your part.

**Comment by demipixel** [comment]
> it ignores rail grid snapping

Shouldn't, this is just a bug that I haven't fixed yet.

**Comment by fwyrl** [comment]
How would it account for rail snapping without some way to know where the grid is? Does the blueprint contain information about that?

**Comment by demipixel** [comment]
The grid is by rails' centers start at 0,0 on the blueprint.

**Comment by fwyrl** [comment]
Interesting. Thanks!

**Comment by demipixel** [comment]
Resolved in newest version.
