### ISSUE TITLE
Issue with China DNS

### ISSUE THREAD

**Issue by demipixel** [demipixel/autotorio#22]
@Suixinlei I set a CNAME Record on namecheap with Host `cn` and Value `autotorio.kouka.tech.` (the trailing period is necessary), but the site doesn't appear on cn.autotorio.com as it does on autotorio.kouka.tech... Any ideas?

**Comment by Suixinlei** [comment]
Sorry, server in china must be put on records.I will redeploy autotorio, then you just need set A record.

**Comment by demipixel** [comment]
Alright, for A record I’ll need an IP.

**Comment by Suixinlei** [comment]
118.184.32.125
Done~This is a HongKong Server.

**Comment by demipixel** [comment]
Seems to be up and running!
