### ISSUE TITLE
Creates impossible blueprints, No turret Power

### ISSUE THREAD

**Issue by fwyrl** [demipixel/autotorio#3]
Input string:

`0eNqNj8EKwjAQRP9lzluwoRaaXxGRVhdZSDelSdVS8u821YOgB4+zzLydWdC5iYdRNMIukLPXAHtYEOSqrcu3OA8MC4ncg6Btn1WIXrm4t84hEUQv/IAt05HAGiUKvyibmE869R2Pq+FXnjD4sEa85m8ZYwgzbFGalOiLYf5iFG9IZqyltvL2YyvhxmPY/HVVmf2uaUxdpfQE499ZXg==`

Using these settings here:

`http://www.autotorio.com/?belt_type=Fast%20Transport%20Belt&undergroundBelts=false&trainDirection=Left&minedOreDirection=Up&minerSpace=2&useStackInserters=true&botBased=false&requestItem=Iron%20Ore&turretType=Laser%20Turrets&turretSpacing=2&walls=true&wallThickness=2&wallSpace=9&exitRoute=true&locomotiveCount=2&cargoWagonCount=8&concrete=None&borderConcrete=None&trackConcrete=None`

With this balancer I whipped up:

`0eNqdl+tqg0AUhN9lf5viXry+Sikll6UsmI3opiQE370aoYQw3XTnl2j0c07OnFn3Jnbd2faD80G0N+H2Jz+K9v0mRvflt91yLVx7K1rhgj2KTPjtcTmzl36w47gJw9aP/WkIm53tgpgy4fzBXkQrp+zfkLHvXAh2eHhcTR+ZsD644Owq6H5y/fTn426+s5WvpGSiP43z4ye/vH9GbkwmrvOhmBZpTziVjlMRnE7H6QjOJOPyCK1IFycjuDIZF/vnqmRaTFudTIu1ofnbuaCfb8WKMggl8xSWjLMk7TYNefww6HmCD26w+/W3EtF1QuV5vHBDOxkXXrBzhnFlQqUqXmnFDhlWVrNT9tRgheANZW0FYzmnrSghT6Zo+3UfZinGyLhMzfYDKzNMB3KIKtgGYGUlG1XytfFURTQEV12zwYKrbshcgTSdk2bBNEkmi3wd9VoxCyZMLE1/UcGB09SEYGXsooGFlazzMI4ZCVxmTfoE62qIpRHqMjm7EYALrZFs3mGcYm2LcZr0GqbRn08YV5AOwbSSTDlMq8iNwEybN6L3bWv7sFXOxLcdxjX4jFFF3jSqnO/9AYoGLUw=`

There are impossible/overlapping parts at the corners, which Factorio autoresolves. It also does not put power lines on the east and west walls, and the lines on the north and south do not get placed, as they are supposed to be placed inside the turrets.

**Comment by demipixel** [comment]
Resolved for next version.
