### ISSUE TITLE
Not connected belts

### ISSUE THREAD

**Issue by Dagda47** [demipixel/autotorio#4]
The following string contains two belts which are not connected via the placed splitter:
https://pastebin.com/uFeFYnEA
The input string was: 
0eNqNkMEKwjAQRP9lzinYWCvmV0Sk1UUC6aYkW7WU/LtNvRQR9DjLzpvZndC6gfpgWWAm2IvnCHOcEO2NG5dnMvYEAyvUQYGbLqsonql4NM4hKVi+0hOmTOqnUULDsfdBipacrMw6nRSIxYqld4VFjGceupbCTP8WrtD7OFs858SM2SqMMEW5T7nNB0P/xSh0tUAyYy61HGBWj1K4U4jLfl1Verc5HHRdpfQCTBVt/A==
I used these settings:
http://www.autotorio.com/outpost?modded=false&belt_type=Fast%20Transport%20Belt&undergroundBelts=false&trainDirection=Right&minedOreDirection=Bottom&minerSpace=0&useStackInserters=true&includeRadar=true&botBased=false&requestItem=Iron%20Ore&turretType=Laser%20Turrets&walls=false&includeTrainStation=true&exitRoute=false&concrete=None&borderConcrete=None&trackConcrete=None

**Comment by demipixel** [comment]
This seems to be resolved.
