### ISSUE TITLE
Train entrance direction isn't limited to valid entries when Top or Bottom is selected for location

### ISSUE THREAD

**Issue by serenewaffles** [demipixel/autotorio#6]
![image](https://cloud.githubusercontent.com/assets/775693/26166967/6b5c59c6-3b03-11e7-9619-ba32276b4c4b.png)
As you can see in the image, when I select "Top" for my station location, the website does not limit me to valid choices.
![image](https://cloud.githubusercontent.com/assets/775693/26166990/7e866514-3b03-11e7-9216-398eed956e5f.png)
When selecting Right or Left for the train station location, train entrance direction is properly limited to valid entries.

**Comment by demipixel** [comment]
Fixed.
