### ISSUE TITLE
Error: buffer error with almost any blueprint

### ISSUE THREAD

**Issue by VlivesRaw** [demipixel/autotorio#7]
Foe example this blueprint throws aforementioned error:
`0eNqdnNtu20YURX+l4LMEcG6cof8hT30sgoKWGYeoRAmU1NYN/O+lI0dS4rG19jwZvm0d7nM/czjfqvv1sd9Nw3io7r5Vw2o77qu7P75V++Fx7NYvPzs87frqrhoO/aZaVGO3efluM6yHQzc9LferoR9X/XLXrf6qnhfVMD70/1Z35vnzourHw3AY+hPg92+e/hyPm/t+mv/gDHWYunG/206H5X2/Pswfsdvu53/bji8fPkMt46J6mr+YdoZ/GKZ+dfqlf168QbUcNXBUx1EtR/UYteagAYMKkjYYtOWgkZP6AzXeRk0cNeVRmwxqqxsrQDU1h20EWKPDptvMGquT8AuszcE63WUTIMHrPktICDossFrTyLGACBtlVCJrkkMMkbWVUYGs9uJh3X7fb+7Xw/i43HSrr8PYL+1b7B/+MJtUNSMPp8w3bcflY99Ny3++9v26yn2QkUMkIMVaGZWQ4vTIGwCs12EbABtEFZ5jWrjW4W7op9XLf07b4/iwnwEeu/9mhKwyG93JyZNEHZbwnmQvJ8K2MiqQ1dWylwNZnZFRiawX59tvuvV62a/nP5+G1XK3Xfdvof1Z4BzYxee+dPvDchj3/XSYf/MuTLidOh33OCc8d9CeO3343A197iQ8d5TDIrGiJKMSNltKwLke9berG1/rsdaBjsTosB7Aip50juAuZ1L+4kofkBk/hPAEIgjEFZSFhLiCRESk1etCIqyeh4isel0IZA16HgKyBqMGeXc72AUrB3kiqpNRCa2+sNx2YrkdgppWCNP6mIMwrScrwnTSI7UBsK0Oa8H8SG3DzrHXXBvGl/lTumnzYe3eFMwVATFNwfCDEIPLwqXLC5sz5KZg9kGELUhyhFp99kGE1XMckVWffRBZ9RwHZI11Wf9icxVTlFMbsNOopzby3HpqAzqKpamtFlNbLGy/8mqT2y+iNj2jEbXp7RdRm57QwNFFKmi/agB7cbLj+NBPj99nVTfSzK/iLs7ndePueMhZWCrIZUR6JzRVbc5ak5C3PFeW6FDnTFtnZRRaMpeVMdfPJ300SFCTnrDr2/6fBJ8yWNi2llGJVbZGrgNqIKyVMzaR1amo7W1ttfKQEPhUy0tBzy2gUUERqVEuB4APtHK2Iqy2cgoEBJi6VkeQ5Hy11meF5BiwtoXHPbH0tMfUTk475Ji01rMZIiioLSPSZqPSbjK0P0792D28w3IE5YHJ0puXWG7FkNIuLrjezgx87eZC7OF2uxPBooOpxR6KKE5Y9nCcBiN3ZsR0r1Y9pB7qZxs7jsvDcZr6bG1rrvY+lPYpPmfB1DEj2Xcx8pgRaUxuypDGklg7v/LQ5OlshZObkIWwtRxUA1ltMjJsQ2BtWeuRp8/Kw8IAAoj1hZHf08hvxQbMfGgAjRr2kf6jiorUn4omcO9ovxWzB1G+sI/hOJtOzkmETWfLsocXsgdf00hZOvILjl4NzYjkoKIikht5d9QRCqI8ckKwqWBg5t8bmG2Ph3cmZsa18pIqOBo0Xs9mCFbPZp7AWl7Be7KhK4870MN7FRU9eygK5dntE3O11iE1GR64hJfHHYjUpKIiUuV5B5FV2O1ouazByBHAEtiCF1YIrD7SQLD6SAORII80LAgvoXSkYWhhG4SRhiES66fLhF35dJno7GqlQ4ph4HzRNOphMzGHRj9sJjTIh82I3NLDZqHUbQrPmbMZrVHPmS0xA/2cmXArT+6RxuQCkcgaaxWVnAdEuTxEsloVFcnqiiYo2aNbc7XDwfIMCdoxlKUZS7PM1Q6HMD7J+2lU5xxI82raQooXxx1EVUmddpCnT+qwgzx9Kpt1WCH+J3HUQRJ3UicdiGB10IEIbtRoReYRyhpH4KhJRSUZS9nicDlZ829x1rgkJkVbq77ZhWRUlzcIna2YqH5QmsXyRbU1qalaeYeXDB1aeSkKoaorvAg0qWtGCJU70wmUvNdZqy+pIFDVozwBteLjI1AneoHLkdBkocn7X1lDzcOpJWA4S3rO1u/dp5L5NLEejK8flsXiLpa4iSURFFkDOTuOWGXC1RsniyXv1Qu7GCdQ8h62UbMVklQdvSNJuVdFoqIyr0plXiVsZSROs+peiOaEPQHRrKYucguTVd0LXYahpi4kqepeSNKiYjC7E2+tL0qDYHfM2iCaJyJUdSREaBTtibxxYoWbM15Ra4KqztuRrPLNGUjWq00NxbgMmLZYZ3E6ICv31rmifPDzK6Q8IThfUmaZ7NzNOtXTmE2orsZsIuL8wvQme5kjUqppi7wtZr3sZURWryYuJqvgXw7oyRf6ly/zL2FPIwlUy46GqG64SyCq5XSG7t+SHY00XvIFHEhW+QIOJOvVkoZQd5l8b3y1miHlRtJ+CvsZSSBVdilEalDNirRGwmUbr6jorjj5fAuhpjJLIO1XaHkUbwCefNVGuMhaEMWF6zYSN47GFtVe2Zc4bCP7GrGJxvOUgPQmJ643fdPnxemO5rurK50X1bqbUeaffXrV6W+/n3Q6/+rvftqfJPJ+DkmN8S/l6/86ucyi`

**Comment by demipixel** [comment]
Gonna put this on high priority. Obviously has something to do with the recent changes making all processing client side. Doesn't happen for all blueprints it appears.

**Comment by demipixel** [comment]
Well that took longer than I thought. So much for my afternoon plans :P (It was just video games)
