### ISSUE TITLE
Flipping Blueprints with Curving Rail Segments Doesn't Behave Well

### ISSUE THREAD

**Issue by Fusty** [demipixel/autotorio#8]
Hello,

This makes some sense, the entire curving section gets flipped about its midpoint, but this doesn't translate to a flipped blueprint.  See the following original blueprint;

![Original Blueprint](http://i.imgur.com/Q6Pwugc.png)

Turns into this blueprint when flipped along the Y axis

![Flipped Blueprint](http://i.imgur.com/OaVvE4P.png)

Just a heads up, this may not be worth fixing in the near term but it is good to catalog issues nonetheless.

**Comment by Fusty** [comment]
Actaully, now that I look at this I think the curved rail sections are just being flipped about the wrong axis.

**Comment by demipixel** [comment]
https://github.com/demipixel/factorio-generators/issues/12

**Comment by Fusty** [comment]
D'oh!

**Comment by Fusty** [comment]
I really thought I saw no open issues.  Sorry to duplicate!

**Comment by demipixel** [comment]
Resolved.
